version: "3.9"

services:

  db:
    image: postgres:15
    restart: always
    environment:
      - POSTGRES_DB=securepayment
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
    ports:
      - "5432:5432"

  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      - DATABASE_URL=postgresql://user:password@db:5432/securepayment?sslmode=disable
      - ADDRESS=:8080
    depends_on:
      - db
